# config_train.yaml

WORK:
  PATH: &work_path "D:\\GitWork\\dog_breed\\"
              
DATA:
  PATH: "D:\\GitWork\\dog_breed\\data\\"
  DIR_TEST: "test"
  DIR_TRAIN: "train"
  CSV_LABELS: "labels.csv"

PROCESSED:
  PATH: "D:\\GitWork\\dog_breed\\processed\\"
  FNAME_BREEDS: "breeds_processed"
  FNAME_LABELS: "labels_processed"
  
PRETRAINED:
  PATH: "D:\\GitWork\\dog_breed\\pretrained\\"
  FNAME_INCEPTION_V3: 'inception_v3-1a9a5a14.pth'
  FNAME_RESNET18: 'resnet18-5c106cde.pth'
  FNAME_RESNET50: 'resnet50-19c8e357.pth'
  FNAME_BEST_MODEL: 'resnet50_20200918-2043_acc95.pth'

OUTPUT:
  PATH: "D:\\GitWork\\dog_breed\\output\\"
  CSV_SUMBMISSION: 'Submission.csv'
  CSV_PREDICTION : 'Prediction.csv'

TRAIN:
  FRAC_FOR_TRAIN: 0.8
  NUM_CLASSES: 16
  BATCH_SIZE: 6
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  STEP_SIZE: 7
  GAMMA: 0.1
  NUM_EPOCHS: 2
  