# config_train.yaml

WORK:
  PATH: &work_path "/home/user/work/dog_breed/"
              
DATA:
  PATH: "/hd_data/dog-breed-identification/"
  PATH_TEST: "/hd_data/dog-breed-identification/test/"
  PATH_TRAIN: "/hd_data/dog-breed-identification/train/"
  FNAME_LABELS: "labels.csv"

PROCESSED:
  PATH: "/home/user/work/dog_breed/processed/"
  FNAME_BREEDS: "breeds_processed"
  FNAME_LABELS: "labels_processed"
  
PRETRAINED:
  PATH: "/home/user/work/dog_breed/pretrained/"
  FNAME_PREMODEL: ''

OUTPUT:
  PATH: "/home/user/work/dog_breed/"

TRAIN:
  FRAC_FOR_TRAIN: 0.8
  NUM_CLASSES: 16
  BATCH_SIZE: 100
  NUM_EPOCHS: 200
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  STEP_SIZE: 7
  GAMMA: 0.1

