# config_train.yaml

WORK:
  PATH: &work_path "D:\\GitWork\\dog_breed\\"
              
DATA:
  PATH: "D:\\GitWork\\dog_breed\\data\\"
  DIR_TEST: "test"
  DIR_TRAIN: "train"

  PATH_RAW:  "D:\\GitWork\\dog_breed\\data\\raw\\"
  CSV_LABELS: "labels.csv"
  CSV_SAMPLE_SUBMISSION: "sample_submission.csv"

PROCESSED:
  PATH: "D:\\GitWork\\dog_breed\\data\\processed\\"
  FNAME_BREEDS: "breeds_processed"
  FNAME_LABELS: "labels_processed"
  
PRETRAINED:
  PATH: "D:\\GitWork\\dog_breed\\models\\"
  FNAME: 'resnet50-19c8e357.pth'

TRAIN:
  FRAC_FOR_TRAIN: 0.8
  NUM_CLASSES: 16
  BATCH_SIZE: 6
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  STEP_SIZE: 7
  GAMMA: 0.1
  NUM_EPOCHS: 2
  